### ISSUE TITLE
Can not save to V1 13.3.4.5278 with the API

### ISSUE THREAD

**Issue by arnaud-adant-ibboost-com** [versionone/VersionOne.SDK.Java.APIClient#10]
services.save(newStory);

com.versionone.apiclient.exceptions.APIException: Error processing response
        at com.versionone.Oid.fromToken(Oid.java:177)
        at com.versionone.apiclient.Services.getOid(Services.java:231)
        at com.versionone.apiclient.Services.parseSaveAssetNode(Services.java:512)
        at com.versionone.apiclient.Services.save(Services.java:314)
        at com.versionone.apiclient.Services.save(Services.java:269)

**Comment by arnaud-adant-ibboost-com** [comment]
Oh, that was a required field allowing the save. Nothing to do with the release.

You really need to handle user exception much better.

Document doc = XMLHandler.buildDocument(reader, path);
parseSaveAssetNode(doc.getDocumentElement(), asset);

you need to check if the response contains an error and throw it to the user. !

**Comment by veplechuc** [comment]
Ok, Thanks for your suggestion. I´ll take a look on that.
